# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u5b57')),
                ('age', models.IntegerField(verbose_name='\u5e74\u9f84')),
                ('is_live', models.BooleanField(verbose_name='\u662f\u5426\u5728\u5f79')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u961f\u540d')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t03.Team', verbose_name='\u5f52\u5c5e\u7403\u961f'),
        ),
    ]
