-- CREATE TABLE basketball(
		-- 										id int auto_increment PRIMARY KEY,
		-- 		 								name VARCHAR(10),
			-- 									age VARCHAR(4),
					-- 							sex VARCHAR(3),
							-- 					fire_out VARCHAR(20)
									-- 			);
-- SELECT name AS 名字,age AS 年龄,sex AS 性别,fire_out AS 火力输出 FROM basketball;-- 起别名
-- INSERT INTO basketball(name,age,sex,fire_out)VALUES("乔丹","55","0","5000"),
-- 																										("科比","45","0","4000"),
-- 																										("艾弗森","47","0","3888"),
-- 																										("库里","30","0","888"),
-- 																										("詹姆斯","32","0","4000");-- 添加
-- DELETE FROM basketball WHERE id=1;-- 删除
-- UPDATE basketball SET name="欧文" WHERE name="库里"-- 修改
-- SELECT DISTINCT name FROM basketball;-- 去重
