# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='身高')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重')),
                ('birthday', models.DateTimeField(auto_now_add=True, verbose_name='出生日期')),
                ('school_state', models.BooleanField(default=True, verbose_name='是否在上学')),
            ],
            options={
                'verbose_name': '人类',
                'db_table': 'Person',
            },
        ),
    ]
