# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wk', '0002_auto_20180814_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
