# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t02', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firecart',
            options={'verbose_name': '\u706b\u8f66\u7c7b'},
        ),
        migrations.AlterField(
            model_name='firecart',
            name='speed',
            field=models.IntegerField(db_column='my_speed', default=300, verbose_name='\u65f6\u901f'),
        ),
        migrations.AlterModelTable(
            name='firecart',
            table='huocart',
        ),
    ]
