# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u59d3\u540d')),
                ('age', models.IntegerField(verbose_name='\u5e74\u9f84')),
                ('set_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65e5\u671f\u8be6\u7ec6\u4fe1\u606f')),
                ('last_update', models.DateField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('is_used', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5728\u7528')),
            ],
            options={
                'db_table': 'aws_users',
                'verbose_name': '\u7528\u6237\u8868',
            },
        ),
    ]
