# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tvideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('playno', models.IntegerField(default=100, verbose_name='播放量')),
                ('birthday', models.DateTimeField(auto_now_add=True, verbose_name='投稿时间')),
            ],
        ),
    ]
