# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw02', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvideo',
            options={'verbose_name': '视频类'},
        ),
        migrations.AlterField(
            model_name='tvideo',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True, db_column='u_day', verbose_name='投稿时间'),
        ),
        migrations.AlterModelTable(
            name='tvideo',
            table='u_video',
        ),
    ]
