# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw02', '0002_auto_20180814_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvideo',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True, db_column='uday', verbose_name='投稿时间'),
        ),
    ]
